POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "5689ce28-d31a-4170-86e3-065ae247e0e0"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "86898669-96f2-401b-a4be-30806dd48e91",
    "account_id_to": "9e4da4e1-4843-4a77-a812-7efcc1e20985",
    "amount": 10
}