POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Mary Doe",
    "email": "mary@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "59ffd194-aad3-40e1-9f11-b86ce39ed6ef"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "79937dcb-2848-4e6a-b9b6-6cce76ecd144",
    "account_id_to": "f8ddf42d-8abe-46b8-93ab-f6b31d4436b8",
    "amount": 10
}