# frozen_string_literal: true

source 'https://rubygems.org'

gem 'mysql2'
gem 'padrino'
gem 'rack'
gem 'rack-protection'
gem 'rack-session'
gem 'rake'
gem 'sequel'
gem 'thin'

group :development do
  gem 'pry'
  gem 'rubocop'
end

group :test do
  gem 'faker'
  gem 'rspec'
end
