AllCops:
  TargetRubyVersion: 3.1.0
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/SuperArguments:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false
